"""update record

Revision ID: 68b3b50675a2
Revises: f79abda44fd8
Create Date: 2025-02-21 16:55:00.360118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b3b50675a2'
down_revision: Union[str, None] = 'f79abda44fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('contact_landline', sa.String(), nullable=True))
    op.drop_column('leaves', 'Contact_landline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('Contact_landline', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('leaves', 'contact_landline')
    # ### end Alembic commands ###
